version: '3.8'

services:
  tele2_market:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  prometheus_data: {}
  grafana_data: {}
